breakblog/blueprints/admin.py
# -*- coding: utf-8 -*-
"""
    :author: tw.huang
    :github_url: https://github.com/tw-huang
    :email: tw.huang@foxmail.com
"""
import os

from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, send_from_directory
from flask_login import login_required, current_user
from flask_ckeditor import upload_success, upload_fail

from breakblog.extensions import db
from breakblog.forms import SettingForm, PostForm, CategoryForm, LinkForm
from breakblog.models import Post, Category, Comment, Link
from breakblog.utils import redirect_back, allowed_file

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form=form)


# p285 文章管理
@admin_bp.route('/post/manage')
@login_required
def manage_post():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['BREAKBLOG_MANAGE_POST_PER_PAGE'])
    posts = pagination.items
    return render_template('admin/manage_post.html', page=page, pagination=pagination, posts=posts)


# p288 创建文章
@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        subtitle = form.subtitle.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, subtitle=subtitle,
                    body=body, category=category)
        # 另一种方法
        # category_id = form.category.data
        # post = Post(title=title, body=body, category_id=category_id)
        db.session.add(post)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    return render_template('admin/new_post.html', form=form)


# p290 编辑文章
@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['BREAKBLOG_MANAGE_POST_PER_PAGE'])

    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        post.subtitle = form.subtitle.data
        post.body = form.body.data
        post.category = Category.query.get(form.category.data)
        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    form.title.data = post.title  # 预定义表单中的title字段值
    form.subtitle.data = post.subtitle
    form.body.data = post.body  # 预定义表单中的body字段值
    form.category.data = post.category_id
    return render_template('admin/edit_post.html', form=form, pagination=pagination)


# p291 删除文章
@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted.', 'success')
    return redirect_back()


# p291 设置评论的开启和关闭状态
@admin_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.', 'success')
    else:
        post.can_comment = True
        flash('Comment enabled.', 'success')
    db.session.commit()
    return redirect_back()


# p295 评论管理
@admin_bp.route('/comment/manage')
@login_required
def manage_comment():
    filter_rule = request.args.get('filter', 'all')  # 从查询字符串获取过滤规则
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BREAKBLOG_COMMENT_PER_PAGE']
    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(reviewed=False)
    elif filter_rule == 'admin':
        filtered_comments = Comment.query.filter_by(from_admin=True)
    else:
        filtered_comments = Comment.query

    pagination = filtered_comments.order_by(
        Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments=comments, pagination=pagination)


# p294 批准评论
@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash('Comment published.', 'success')
    return redirect_back()


# 删除评论
@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'success')
    return redirect_back()


# p297 分类管理
@admin_bp.route('/category/manage')
@login_required
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Category created.', 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not edit the default category.', 'warning')
        return redirect(url_for('blog.index'))
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category updated.', 'success')
        return redirect(url_for('.manage_category'))

    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not delete the default category.', 'warning')
        return redirect(url_for('blog.index'))
    category.delete()  # 调用category对象的delete()方法删除分类
    flash('Category deleted.', 'success')
    return redirect(url_for('.manage_category'))


@admin_bp.route('/link/manage')
@login_required
def manage_link():
    return render_template('admin/manage_link.html')


@admin_bp.route('/link/new', methods=['GET', 'POST'])
@login_required
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        name = form.name.data
        url = form.url.data
        link = Link(name=name, url=url)
        db.session.add(link)
        db.session.commit()
        flash('Link created.', 'success')
        return redirect(url_for('.manage_link'))
    return render_template('admin/new_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_link(link_id):
    form = LinkForm()
    link = Link.query.get_or_404(link_id)
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        db.session.commit()
        flash('Link updated.', 'success')
        return redirect(url_for('.manage_link'))
    form.name.data = link.name
    form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
@login_required
def delete_link(link_id):
    link = Link.query.get_or_404(link_id)
    db.session.delete(link)
    db.session.commit()
    flash('Link deleted.', 'success')
    return redirect(url_for('.manage_link'))


@admin_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['BREAKBLOG_UPLOAD_PATH'], filename)


@admin_bp.route('/upload', methods=['POST'])
def upload_image():
    f = request.files.get('upload')
    if not allowed_file(f.filename):
        return upload_fail('Image only!')
    f.save(os.path.join(
        current_app.config['BREAKBLOG_UPLOAD_PATH'], f.filename))
    url = url_for('.get_image', filename=f.filename)
    return upload_success(url, f.filename)

breakblog/blueprints/blog.py
# -*- coding: utf-8 -*-
"""
    :author: tw.huang
    :github_url: https://github.com/tw-huang
    :email: tw.huang@foxmail.com
"""
from flask import Blueprint, render_template, request, current_app, flash, redirect, url_for
from flask_login import current_user

from breakblog.emails import send_new_reply_email, send_new_comment_email
from breakblog.extensions import db
from breakblog.forms import AdminCommentForm, CommentForm
from breakblog.models import Post, Category, Comment
from breakblog.utils import redirect_back

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/')
def index():
    # p254 获取分页记录
    page = request.args.get('page', 1, type=int)  # 从查询字符串获取当前页面
    per_page = current_app.config['BREAKBLOG_POST_PER_PAGE']  # 每页文章数量
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=per_page)  # 分页对象
    posts = pagination.items  # 当前页数的记录列表
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')


# p258 p263 p266 显示文章正文、显示评论列表、发表评论与回复
@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    # p258 get_or_404()方法查询指定id记录，没有就返回404错误
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BREAKBLOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    comments = pagination.items
    post.pageview = post.pageview + 1  # 文章浏览量+1
    db.session.commit()  # p151 更新记录直接赋值，然后commit()即可

    # current_user.is_authenticated 从 flask-login 包导入
    if current_user.is_authenticated:  # p267 如果当前用户已登录，使用管理员表单
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['BREAKBLOG_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            from_admin=from_admin, post=post, reviewed=reviewed)
        replied_id = request.args.get('reply')
        if replied_id:  # 如果url中reply查询参数存在，那么说明是回复
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)  # 发送邮件给被回复用户
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:  # 根据登录状态显示不同的提示信息
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            send_new_comment_email(post)  # 发送提醒邮件给管理员
        return redirect(url_for('.show_post', post_id=post_id))
    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)


# p262 显示分类文章列表
@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BREAKBLOG_POST_PER_PAGE']
    # with_parent()查询方法传入分类对象，筛选出属于该分类的所有文章记录
    pagination = Post.query.with_parent(category).order_by(
        Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)


# p263 p267 显示评论列表、支持回复评论
@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash('Comment is disabled.', 'warning')
        return redirect(url_for('.show_post', post_id=comment.post.id))
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author) + '#comment-form')


# p269 主题切换
# @blog_bp.route('/change-theme/<theme_name>')
# def change_theme(theme_name):
#     if theme_name not in current_app.config['BREAKBLOG_THEMES'].keys():
#         abort(404)
#
#     response = make_response(redirect_back())
#     response.set_cookie('theme', theme_name, max_age=30 * 24 * 60 * 60)  # max_age参数设置cookie过期时间为30天
#     return response

breakblog/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <div>
            <h4 class="text-primary"><a href="{{ url_for('.show_post', post_id=post.id) }}">{{ post.title }}</a>
            </h4>
            <p class="text-muted my-2">
                {# p252 truncate 过滤器，截取正文开头一部分，默认255个字符，作为文章摘要 #}
                {# p252 striptags 过滤器，过滤文章正文中的html标签 #}
                {# {{ post.body|striptags|truncate }} #}
                {{ post.subtitle }}
                <small>...<a href="{{ url_for('.show_post', post_id=post.id) }}">Read More</a></small>
            </p>
             <div>
                <small>
                    <span class="oi oi-eye"></span>
                    {{ post.pageview }}&nbsp;&nbsp;
                    <span class="oi oi-book "></span>
                    <a href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>&nbsp;&nbsp;
                    <span class="oi oi-person"></span>
                    <a href="{{ url_for('.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>
                </small>
                <small class="float-right">
                    <span class="oi oi-clock"></span>
                    {{ moment(post.timestamp).format('LL') }}
                </small>
            </div>
        </div>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
    <hr>
{% else %}
    <div class="tip">
        <h4>No posts yet.</h4>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('admin.new_post') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}

breakblog/templates/blog/_sidebar.html
{% if categories %}
    <div class="card mb-3">
        <div class="card-header"><span class="oi oi-list"></span> Categories</div>
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <div>
                        <span class="oi oi-tags tex"></span>
                        <a href="{{ url_for('blog.show_category', category_id=category.id) }}"> {{ category.name }}</a>
                    </div>
                    <span class="badge bg-light badge-pill"> {{ category.posts|length }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
{% if links %}
    <div class="card">
        <div class="card-header"><span class="oi oi-link-intact"></span> Links</div>
        <ul class="list-group list-group-flush">
            {% for link in links %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <div>
                        <span class="oi oi-external-link"></span>
                        <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

breakblog/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-12 p-3 bg-white">
            <h2>About</h2>
            <h6 class="text-muted">{{ admin.blog_sub_title|default('Blog Subtitle') }}</h6>
            <div class="float-right text-muted">
                -- {{ admin.name }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9 col-12 p-3 bg-white mt-3">
            <h3>{{ admin.about|safe }}</h3>
        </div>
        <div class="col-lg-3 col-12 pr-lg-0 mt-3">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

breakblog/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-12 p-3 bg-white">
            <h2>Category: {{ category.name }}</h2>
            <h6 class="text-muted">Total {{ category.posts|length }} posts</h6>
            <div class="float-right text-muted">
                -- {{ admin.blog_sub_title|default('Blog Subtitle') }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9 col-12 p-3 bg-white mt-3">
            {% include "blog/_posts.html" %}
            {% if posts %}
                <div class="page-footer">{{ render_pagination(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-lg-3 col-12 pr-lg-0 mt-3">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

breakblog/templates/blog/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pager %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-12 p-3 bg-white">
            <h2>{{ admin.blog_title|default('Blog Title') }}</h2>
            <h6 class="text-muted">{{ admin.blog_sub_title|default('Blog Subtitle') }}</h6>
            <div class="float-right text-muted">-- {{ admin.name }}</div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9 col-12 p-3 bg-white mt-3">
            {% include "blog/_posts.html" %}
            {% if posts %}
                <div class="pag">{{ render_pager(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-lg-3 col-12 pr-lg-0 mt-3">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

breakblog/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-12 p-3 bg-white">
            <h2>{{ post.title }}</h2>
            <h6 class="text-muted">Category: <a href="{{ url_for('.show_category', category_id=post.category.id) }}">
                {{ post.category.name }}</a>&nbsp;&nbsp; Date: {{ moment(post.timestamp).format('LLL') }}</h6>
            {% if current_user.is_authenticated %}
                <div class="btn-group float-right btn-group-sm">
                    <a href="{{ url_for('admin.edit_post', post_id=post.id) }}">
                        <button type="button" class="btn btn-info btn-sm p-1">Edit</button>
                    </a>
                    <form class="inline" method="post"
                          action="{{ url_for('admin.delete_post', post_id=post.id, next=url_for('blog.index')) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="submit" class="btn btn-danger btn-sm p-1"
                                onclick="return confirm('Are you sure?')">
                            Delete
                        </button>
                    </form>
                </div>
            {% else %}
                <div class="float-right text-muted">-- {{ admin.name }}</div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9 col-12 p-3 bg-white mt-3">
            <article>
                {{ post.body|safe }}
            </article>
            <hr>
            <button type="button" data-toggle="modal" data-target=".postLinkModal" class="btn oi oi-share"> Share
            </button>
            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" class="form-control"
                                       value="{{ url_for('.show_post', post_id=post.id, _external=True) }}" readonly>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments py-3" id="comments">
                <h3 class="py-3">Total: {{ pagination.total }} comments
                    <p class="float-right">
                        <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">
                            Latest</a>
                    </p>
                </h3>
                {% if current_user.is_authenticated %}
                    <form class="" method="post"
                          action="{{ url_for('admin.set_comment', post_id=post.id, next=request.full_path) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="submit" class="btn btn-block btn-sm  btn-warning p-1 mb-4">
                            {% if post.can_comment %}Disable{% else %}Enable{% endif %} Comment
                        </button>
                    </form>
                {% endif %}
                </h3>
                {% if comments %}
                    <ul class="list-group">
                        {% for comment in comments %}
                            <li class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5>
                                        <a href="{% if comment.site %}{{ comment.site }}{% else %}#{% endif %}"
                                           target="_blank" title="{% if comment.site %}{{ comment.site }}{% endif %}">
                                            {% if comment.from_admin %}
                                                {{ admin.name }}
                                            {% else %}
                                                {{ comment.author }}
                                            {% endif %}
                                        </a>
                                        {% if comment.from_admin %}
                                            <span class="badge badge-pill bg-gary">Author</span>{% endif %}
                                        {% if comment.replied %}<span class="badge badge-light">Reply</span>{% endif %}
                                    </h5>
                                    <div class="btn-group">
                                        <a href="{{ url_for('.reply_comment', comment_id=comment.id) }}">
                                            <button type="button" class="btn btn-sm p-1">
                                                <span class="oi oi-chat"></span> Reply
                                            </button>
                                        </a>
                                        {% if current_user.is_authenticated %}
                                            <a href="mailto:{{ comment.email }}">
                                                <button type="button" class="btn btn-info btn-sm p-1">Email</button>
                                            </a>
                                            <form class="inline" method="post"
                                                  action="{{ url_for('admin.delete_comment', comment_id=comment.id, next=request.full_path) }}">
                                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                                <button type="submit" class="btn btn-danger btn-sm p-1"
                                                        onclick="return confirm('Are you sure?')">
                                                    Delete
                                                </button>
                                            </form>
                                        {% endif %}
                                    </div>
                                </div>
                                {% if comment.replied %}
                                    <p class="alert alert-light reply-body my-2 py-2 px-3">{{ comment.replied.author }}
                                        <br>{{ comment.replied.body }}
                                    </p>
                                {%- endif -%}
                                <p class="my-2">{{ comment.body }}</p>
                                {# p211 #}
                                <small class="float-right" data-toggle="tooltip" data-placement="top"
                                       data-delay="500"
                                       data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
                                    {{ moment(comment.timestamp).fromNow() }}
                                </small>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="tip"><h5 class="mb-0">No comments.</h5></div>
                {% endif %}
            </div>
            {% if comments %}
                {{ render_pagination(pagination, fragment='#comments') }}
            {% endif %}
            {% if request.args.get('reply') %}
                <div class="alert alert-secondary mb-0 mt-4">
                    Reply to <strong>{{ request.args.get('author') }}</strong> :
                    <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">Cancel</a>
                </div>
            {% endif %}
            <hr>
            {% if post.can_comment %}
                <div id="comment-form">
                    {{ render_form(form, action=request.full_path) }}
                </div>
            {% else %}
                <div class="tip text-info"><h5>Comment disabled.</h5></div>
            {% endif %}
        </div>
        <div class="col-lg-3 col-12 pr-lg-0 mt-3">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}